server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location /comunicamais/ {
        try_files $uri $uri/ /comunicamais/index.html;
    }

    # Redirecionar reqs sem a barra se cair no diretório
    location = /comunicamais {
        return 301 /comunicamais/;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
