import React from 'react';
import {
    Utensils, Heart, Home, MessageCircle, AlertCircle, Smile, Frown, ThumbsUp, ThumbsDown, Battery, User, Star, Coffee, Bed, Bath,
    Hand, ArrowRight, Play, Eye, DoorOpen, Users, Search, MapPin, ArrowUpRight, Pointer, HeartHandshake, HelpCircle, Maximize2, Minimize2, Plus, XCircle,
    Tv, Trees, Sofa, Moon, BatteryLow, Fingerprint, Activity, DoorClosed, Trophy, TrendingDown, Sun, CloudSun
} from 'lucide-react';

export const QuoteSymbols = [
    // Sociais
    { id: 1, label: { pt: 'Olá', en: 'Hello', es: 'Hola', de: 'Hallo', fr: 'Bonjour', zh: '你好', ja: 'こんにちは' }, icon: <MessageCircle />, colorfulIcon: 'ola.png', category: 'social', text: { pt: 'Olá', en: 'Hello', es: 'Hola', de: 'Hallo', fr: 'Bonjour', zh: '你好', ja: 'こんにちは' }, audio: 'ola.mp3' },
    { id: 3, label: { pt: 'Sim', en: 'Yes', es: 'Sí', de: 'Ja', fr: 'Oui', zh: '是', ja: 'はい' }, icon: <ThumbsUp />, colorfulIcon: 'sim.png', category: 'social', text: { pt: 'Sim', en: 'Yes', es: 'Sí', de: 'Ja', fr: 'Oui', zh: '是', ja: 'はい' }, audio: 'sim.mp3' },
    { id: 4, label: { pt: 'Não', en: 'No', es: 'No', de: 'Nein', fr: 'Non', zh: '不', ja: 'いいえ' }, icon: <ThumbsDown />, colorfulIcon: 'nao.png', category: 'social', text: { pt: 'Não', en: 'No', es: 'No', de: 'Nein', fr: 'Non', zh: '不', ja: 'いいえ' }, audio: 'nao.mp3' },
    { id: 13, label: { pt: 'Ajuda', en: 'Help', es: 'Ayuda', de: 'Hilfe', fr: 'Aide', zh: '帮助', ja: '助けて' }, icon: <HeartHandshake />, colorfulIcon: 'ajuda.png', category: 'social', text: { pt: 'ajuda', en: 'help', es: 'ayuda', de: 'hilfe', fr: 'aide', zh: '帮助', ja: '助けて' }, audio: 'ajuda.mp3' },
    { id: 15, label: { pt: 'Por quê?', en: 'Why?', es: '¿Por qué?', de: 'Warum?', fr: 'Pourquoi?', zh: '为什么?', ja: 'なぜ?' }, icon: <HelpCircle />, colorfulIcon: 'o_que.png', category: 'social', text: { pt: 'por quê', en: 'why', es: 'por qué', de: 'warum', fr: 'pourquoi', zh: '为什么', ja: 'なぜ' }, audio: 'por quê?' },
    { id: 46, label: { pt: 'Bom dia', en: 'Good morning', es: 'Buenos días', de: 'Guten Morgen', fr: 'Bonjour', zh: '早上好', ja: 'おはよう' }, icon: <Sun />, colorfulIcon: 'bom_dia.png', category: 'social', text: { pt: 'bom dia', en: 'good morning', es: 'buenos días', de: 'guten morgen', fr: 'bonjour', zh: '早上好', ja: 'おはよう' }, audio: 'bom_dia.mp3' },
    { id: 47, label: { pt: 'Boa tarde', en: 'Good afternoon', es: 'Buenas tardes', de: 'Guten Tag', fr: 'Bonne après-midi', zh: '下午好', ja: 'こんにちは' }, icon: <CloudSun />, colorfulIcon: 'boa_tarde.png', category: 'social', text: { pt: 'boa tarde', en: 'good afternoon', es: 'buenas tardes', de: 'guten tag', fr: 'bonne après-midi', zh: '下午好', ja: 'こんにちは' }, audio: 'boa_tarde.mp3' },
    { id: 48, label: { pt: 'Boa noite', en: 'Good night', es: 'Buenas noches', de: 'Gute Nacht', fr: 'Bonne nuit', zh: '晚安', ja: 'おやすみ' }, icon: <Moon />, colorfulIcon: 'boa_noite.png', category: 'social', text: { pt: 'boa noite', en: 'good night', es: 'buenas noches', de: 'gute nacht', fr: 'bonne nuit', zh: '晚安', ja: 'おやすみ' }, audio: 'boa_noite.mp3' },
    { id: 49, label: { pt: 'Tchau', en: 'Goodbye', es: 'Adiós', de: 'Tschüss', fr: 'Au revoir', zh: '再见', ja: 'さようなら' }, icon: <Hand />, colorfulIcon: 'tchau.png', category: 'social', text: { pt: 'tchau', en: 'goodbye', es: 'adiós', de: 'tschüss', fr: 'au revoir', zh: '再见', ja: 'さようなら' }, audio: 'tchau.mp3' },

    // Pessoas
    { id: 2, label: { pt: 'Eu', en: 'I', es: 'Yo', de: 'Ich', fr: 'Je', zh: '我', ja: '私' }, icon: <User />, colorfulIcon: 'eu.png', category: 'people', text: { pt: 'Eu', en: 'I', es: 'Yo', de: 'Ich', fr: 'Je', zh: '我', ja: '私' }, audio: 'eu.mp3' },
    { id: 16, label: { pt: 'Você', en: 'You', es: 'Tú', de: 'Du', fr: 'Tu', zh: '你', ja: 'あなた' }, icon: <Users />, colorfulIcon: 'voce.png', category: 'people', text: { pt: 'você', en: 'you', es: 'tú', de: 'du', fr: 'tu', zh: '你', ja: 'あなた' }, audio: 'voce.mp3' },
    { id: 17, label: { pt: 'Quem', en: 'Who', es: 'Quién', de: 'Wer', fr: 'Qui', zh: '谁', ja: '誰' }, icon: <Search />, colorfulIcon: 'quem.png', category: 'people', text: { pt: 'quem', en: 'who', es: 'quién', de: 'wer', fr: 'qui', zh: '谁', ja: '誰' }, audio: 'quem.mp3' },
    { id: 42, label: { pt: 'Mamãe', en: 'Mom', es: 'Mamá', de: 'Mama', fr: 'Maman', zh: '妈妈', ja: 'ママ' }, icon: <User />, colorfulIcon: 'mamae.png', category: 'people', text: { pt: 'mamãe', en: 'mom', es: 'mamá', de: 'mama', fr: 'maman', zh: '妈妈', ja: 'ママ' }, audio: 'mamae.mp3' },
    { id: 43, label: { pt: 'Papai', en: 'Dad', es: 'Papá', de: 'Papa', fr: 'Papa', zh: '爸爸', ja: 'パパ' }, icon: <User />, colorfulIcon: 'papai.png', category: 'people', text: { pt: 'papai', en: 'dad', es: 'papá', de: 'papa', fr: 'papa', zh: '爸爸', ja: 'パパ' }, audio: 'papai.mp3' },
    { id: 44, label: { pt: 'Vovô', en: 'Grandpa', es: 'Abuelo', de: 'Opa', fr: 'Papi', zh: '爷爷', ja: 'おじいちゃん' }, icon: <User />, colorfulIcon: 'vovo_m.png', category: 'people', text: { pt: 'vovô', en: 'grandpa', es: 'abuelo', de: 'opa', fr: 'papi', zh: '爷爷', ja: 'おじいちゃん' }, audio: 'vovo_m.mp3' },
    { id: 45, label: { pt: 'Vovó', en: 'Grandma', es: 'Abuela', de: 'Oma', fr: 'Mamie', zh: '奶奶', ja: 'おばあちゃん' }, icon: <User />, colorfulIcon: 'vovo_f.png', category: 'people', text: { pt: 'vovó', en: 'grandma', es: 'abuela', de: 'oma', fr: 'mamie', zh: '奶奶', ja: 'おばあちゃん' }, audio: 'vovo_f.mp3' },

    // Ações (Verbs)
    { id: 18, label: { pt: 'Querer', en: 'Want', es: 'Querer', de: 'Wollen', fr: 'Vouloir', zh: '想要', ja: '欲しい' }, icon: <Hand />, colorfulIcon: 'querer.png', category: 'verb', text: { pt: 'querer', en: 'want', es: 'querer', de: 'wollen', fr: 'vouloir', zh: '想要', ja: '欲しい' }, audio: 'querer.mp3' },
    { id: 14, label: { pt: 'Gostar', en: 'Like', es: 'Gustar', de: 'Mögen', fr: 'Aimer', zh: '喜欢', ja: '好き' }, icon: <Heart />, colorfulIcon: 'gostar.png', category: 'verb', text: { pt: 'gostar', en: 'like', es: 'gustar', de: 'mögen', fr: 'aimer', zh: '喜欢', ja: '好き' }, audio: 'gostar.mp3' },
    { id: 5, label: { pt: 'Comer', en: 'Eat', es: 'Comer', de: 'Essen', fr: 'Manger', zh: '吃', ja: '食べる' }, icon: <Utensils />, colorfulIcon: 'comer.png', category: 'verb', text: { pt: 'comer', en: 'eat', es: 'comer', de: 'essen', fr: 'manger', zh: '吃', ja: '食べる' }, audio: 'comer.mp3' },
    { id: 6, label: { pt: 'Beber', en: 'Drink', es: 'Beber', de: 'Trinken', fr: 'Boire', zh: '喝', ja: '飲む' }, icon: <Coffee />, colorfulIcon: 'beber.png', category: 'verb', text: { pt: 'beber', en: 'drink', es: 'beber', de: 'trinken', fr: 'boire', zh: '喝', ja: '飲む' }, audio: 'beber.mp3' },
    { id: 19, label: { pt: 'Ir', en: 'Go', es: 'Ir', de: 'Gehen', fr: 'Aller', zh: '去', ja: '行く' }, icon: <ArrowRight />, colorfulIcon: 'ir.png', category: 'verb', text: { pt: 'ir', en: 'go', es: 'ir', de: 'gehen', fr: 'aller', zh: '去', ja: '行く' }, audio: 'ir.mp3' },
    { id: 20, label: { pt: 'Fazer', en: 'Do', es: 'Hacer', de: 'Machen', fr: 'Faire', zh: '做', ja: 'する' }, icon: <Play />, colorfulIcon: 'fazer.png', category: 'verb', text: { pt: 'fazer', en: 'do', es: 'hacer', de: 'machen', fr: 'faire', zh: '做', ja: 'する' }, audio: 'fazer.mp3' },
    { id: 21, label: { pt: 'Ver', en: 'See', es: 'Ver', de: 'Sehen', fr: 'Voir', zh: '看', ja: '見る' }, icon: <Eye />, colorfulIcon: 'ver.png', category: 'verb', text: { pt: 'ver', en: 'see', es: 'ver', de: 'sehen', fr: 'voir', zh: '看', ja: '見る' }, audio: 'ver.mp3' },
    { id: 22, label: { pt: 'Abrir', en: 'Open', es: 'Abrir', de: 'Öffnen', fr: 'Ouvrir', zh: '打开', ja: '開ける' }, icon: <DoorOpen />, colorfulIcon: 'abrir.png', category: 'verb', text: { pt: 'abrir', en: 'open', es: 'abrir', de: 'öffnen', fr: 'ouvrir', zh: '打开', ja: '開ける' }, audio: 'abrir.mp3' },
    { id: 8, label: { pt: 'Dormir', en: 'Sleep', es: 'Dormir', de: 'Schlafen', fr: 'Dormir', zh: '睡觉', ja: '寝る' }, icon: <Bed />, colorfulIcon: 'dormir.png', category: 'verb', text: { pt: 'dormir', en: 'sleep', es: 'dormir', de: 'schlafen', fr: 'dormir', zh: '睡觉', ja: '寝る' }, audio: 'dormir.mp3' },
    { id: 9, label: { pt: 'Brincar', en: 'Play', es: 'Jugar', de: 'Spielen', fr: 'Jouer', zh: '玩', ja: '遊ぶ' }, icon: <Star />, colorfulIcon: 'brincar.png', category: 'verb', text: { pt: 'brincar', en: 'play', es: 'jugar', de: 'spielen', fr: 'jouer', zh: '玩', ja: '遊ぶ' }, audio: 'brincar.mp3' },
    { id: 37, label: { pt: 'Sou', en: 'I am', es: 'Soy', de: 'Ich bin', fr: 'Je suis', zh: '我是', ja: '私は' }, icon: <Fingerprint />, colorfulIcon: 'sou.png', category: 'verb', text: { pt: 'sou', en: 'i am', es: 'soy', de: 'ich bin', fr: 'je suis', zh: '我是', ja: '私は' }, audio: 'sou.mp3' },
    { id: 38, label: { pt: 'Estou', en: 'I am (state)', es: 'Estoy', de: 'Ich bin (Zustand)', fr: 'Je suis (état)', zh: '我在', ja: '私はいます' }, icon: <Activity />, colorfulIcon: 'estou.png', category: 'verb', text: { pt: 'estou', en: 'i am', es: 'estoy', de: 'ich bin', fr: 'je suis', zh: '我在', ja: '私はいます' }, audio: 'estou.mp3' },
    { id: 39, label: { pt: 'Fechar', en: 'Close', es: 'Cerrar', de: 'Schließen', fr: 'Fermer', zh: '关闭', ja: '閉める' }, icon: <DoorClosed />, colorfulIcon: 'fechar.png', category: 'verb', text: { pt: 'fechar', en: 'close', es: 'cerrar', de: 'schließen', fr: 'fermer', zh: '关闭', ja: '閉める' }, audio: 'fechar.mp3' },
    { id: 40, label: { pt: 'Ganhei', en: 'I won', es: 'Gané', de: 'Ich habe gewonnen', fr: 'J\'ai gagné', zh: '我赢了', ja: '勝った' }, icon: <Trophy />, colorfulIcon: 'ganhei.png', category: 'verb', text: { pt: 'ganhei', en: 'i won', es: 'gané', de: 'ich habe gewonnen', fr: 'j\'ai gagné', zh: '我赢了', ja: '勝った' }, audio: 'ganhei.mp3' },
    { id: 41, label: { pt: 'Perdi', en: 'I lost', es: 'Perdí', de: 'Ich habe verloren', fr: 'J\'ai perdu', zh: '我输了', ja: '負けた' }, icon: <TrendingDown />, colorfulIcon: 'perdi.png', category: 'verb', text: { pt: 'perdi', en: 'i lost', es: 'perdí', de: 'ich habe verloren', fr: 'j\'ai perdu', zh: '我输了', ja: '負けた' }, audio: 'perdi.mp3' },

    // Lugares / Espaço
    { id: 7, label: { pt: 'Banheiro', en: 'Bathroom', es: 'Baño', de: 'Badezimmer', fr: 'Salle de bain', zh: '浴室', ja: 'トイレ' }, icon: <Bath />, colorfulIcon: 'banheiro.png', category: 'noun', text: { pt: 'banheiro', en: 'bathroom', es: 'baño', de: 'badezimmer', fr: 'salle de bain', zh: '浴室', ja: 'トイレ' }, audio: 'banheiro.mp3' },
    { id: 23, label: { pt: 'Aqui', en: 'Here', es: 'Aquí', de: 'Hier', fr: 'Ici', zh: '这里', ja: 'ここ' }, icon: <MapPin />, colorfulIcon: 'aqui.png', category: 'adj', text: { pt: 'aqui', en: 'here', es: 'aquí', de: 'hier', fr: 'ici', zh: '这里', ja: 'ここ' }, audio: 'aqui.mp3' },
    { id: 24, label: { pt: 'Lá', en: 'There', es: 'Allí', de: 'Dort', fr: 'Là-bas', zh: '那里', ja: 'あそこ' }, icon: <ArrowUpRight />, colorfulIcon: 'la.png', category: 'adj', text: { pt: 'lá', en: 'there', es: 'allí', de: 'dort', fr: 'là-bas', zh: '那里', ja: 'あそこ' }, audio: 'la.mp3' },
    { id: 25, label: { pt: 'Isso', en: 'This', es: 'Eso', de: 'Das', fr: 'Ça', zh: '这个', ja: 'これ' }, icon: <Pointer />, colorfulIcon: 'isso.png', category: 'adj', text: { pt: 'isso', en: 'this', es: 'eso', de: 'das', fr: 'ça', zh: '这个', ja: 'これ' }, audio: 'isso.mp3' },

    // Qualidades / Descritivos
    { id: 26, label: { pt: 'Grande', en: 'Big', es: 'Grande', de: 'Groß', fr: 'Grand', zh: '大', ja: '大きい' }, icon: <Maximize2 />, colorfulIcon: 'grande.png', category: 'adj', text: { pt: 'grande', en: 'big', es: 'grande', de: 'groß', fr: 'grand', zh: '大', ja: '大きい' }, audio: 'grande.mp3' },
    { id: 27, label: { pt: 'Pequeno', en: 'Small', es: 'Pequeño', de: 'Klein', fr: 'Petit', zh: '小', ja: '小さい' }, icon: <Minimize2 />, colorfulIcon: 'pequeno.png', category: 'adj', text: { pt: 'pequeno', en: 'small', es: 'pequeño', de: 'klein', fr: 'petit', zh: '小', ja: '小さい' }, audio: 'pequeno.mp3' },
    { id: 28, label: { pt: 'Mais', en: 'More', es: 'Más', de: 'Mehr', fr: 'Plus', zh: '更多', ja: 'もっと' }, icon: <Plus />, colorfulIcon: 'mais.png', category: 'adj', text: { pt: 'mais', en: 'more', es: 'más', de: 'mehr', fr: 'plus', zh: '更多', ja: 'もっと' }, audio: 'mais.mp3' },
    { id: 29, label: { pt: 'Acabou', en: 'Finished', es: 'Acabó', de: 'Fertig', fr: 'Fini', zh: '完成', ja: '終わり' }, icon: <XCircle />, colorfulIcon: 'acabou.png', category: 'adj', text: { pt: 'acabou', en: 'finished', es: 'acabó', de: 'fertig', fr: 'fini', zh: '完成', ja: '終わり' }, audio: 'acabou.mp3' },

    // Sentimentos
    { id: 10, label: { pt: 'Feliz', en: 'Happy', es: 'Feliz', de: 'Glücklich', fr: 'Heureux', zh: '快乐', ja: '幸せ' }, icon: <Smile />, colorfulIcon: 'feliz.png', category: 'feelings', text: { pt: 'feliz', en: 'happy', es: 'feliz', de: 'glücklich', fr: 'heureux', zh: '快乐', ja: '幸せ' }, audio: 'feliz.mp3' },
    { id: 11, label: { pt: 'Triste', en: 'Sad', es: 'Triste', de: 'Traurig', fr: 'Triste', zh: '伤心', ja: '悲しい' }, icon: <Frown />, colorfulIcon: 'triste.png', category: 'feelings', text: { pt: 'triste', en: 'sad', es: 'triste', de: 'traurig', fr: 'triste', zh: '伤心', ja: '悲しい' }, audio: 'triste.mp3' },
    { id: 12, label: { pt: 'Dor', en: 'Pain', es: 'Dolor', de: 'Schmerz', fr: 'Douleur', zh: '痛', ja: '痛み' }, icon: <AlertCircle />, colorfulIcon: 'dor.png', category: 'feelings', text: { pt: 'dor', en: 'pain', es: 'dolor', de: 'schmerz', fr: 'douleur', zh: '痛', ja: '痛み' }, audio: 'dor.mp3' },
    { id: 35, label: { pt: 'Sono', en: 'Sleepy', es: 'Sueño', de: 'Müde', fr: 'Sommeil', zh: '困', ja: '眠い' }, icon: <Moon />, colorfulIcon: 'sono.png', category: 'feelings', text: { pt: 'sono', en: 'sleepy', es: 'sueño', de: 'müde', fr: 'sommeil', zh: '困', ja: '眠い' }, audio: 'sono.mp3' },
    { id: 36, label: { pt: 'Cansado', en: 'Tired', es: 'Cansado', de: 'Erschöpft', fr: 'Fatigué', zh: '累', ja: '疲れた' }, icon: <BatteryLow />, colorfulIcon: 'cansado.png', category: 'feelings', text: { pt: 'cansado', en: 'tired', es: 'cansado', de: 'erschöpft', fr: 'fatigué', zh: '累', ja: '疲れた' }, audio: 'cansado.mp3' },

    // Lugares Adicionais
    { id: 30, label: { pt: 'Casa', en: 'Home', es: 'Casa', de: 'Zuhause', fr: 'Maison', zh: '家', ja: '家' }, icon: <Home />, colorfulIcon: 'casa.png', category: 'noun', text: { pt: 'casa', en: 'home', es: 'casa', de: 'zuhause', fr: 'maison', zh: '家', ja: '家' }, audio: 'casa.mp3' },
    { id: 31, label: { pt: 'Cozinha', en: 'Kitchen', es: 'Cocina', de: 'Küche', fr: 'Cuisine', zh: '厨房', ja: 'キッチン' }, icon: <Utensils />, colorfulIcon: 'cozinha.png', category: 'noun', text: { pt: 'cozinha', en: 'kitchen', es: 'cocina', de: 'küche', fr: 'cuisine', zh: '厨房', ja: 'キッチン' }, audio: 'cozinha.mp3' },
    { id: 32, label: { pt: 'Quarto', en: 'Bedroom', es: 'Habitación', de: 'Schlafzimmer', fr: 'Chambre', zh: '卧室', ja: 'ベッドルーム' }, icon: <Bed />, colorfulIcon: 'quarto.png', category: 'noun', text: { pt: 'quarto', en: 'bedroom', es: 'habitación', de: 'schlafzimmer', fr: 'chambre', zh: '卧室', ja: 'ベッドルーム' }, audio: 'quarto.mp3' },
    { id: 33, label: { pt: 'Sala', en: 'Living Room', es: 'Sala', de: 'Wohnzimmer', fr: 'Salon', zh: '客厅', ja: 'リビング' }, icon: <Tv />, colorfulIcon: 'sala.png', category: 'noun', text: { pt: 'sala', en: 'living room', es: 'sala', de: 'wohnzimmer', fr: 'salon', zh: '客厅', ja: 'リビング' }, audio: 'sala.mp3' },
    { id: 34, label: { pt: 'Pátio', en: 'Yard', es: 'Patio', de: 'Hof', fr: 'Jardin', zh: '院子', ja: '庭' }, icon: <Trees />, colorfulIcon: 'patio.png', category: 'noun', text: { pt: 'pátio', en: 'yard', es: 'patio', de: 'hof', fr: 'jardin', zh: '院子', ja: '庭' }, audio: 'patio.mp3' },
];
